// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnvo13eSeBf5F-IN56Yyxw7CkAJAJVD60',
    appId: '1:234402254994:web:aa7e8674ad436426ebd64b',
    messagingSenderId: '234402254994',
    projectId: 'bookstore-c7f2d',
    authDomain: 'bookstore-c7f2d.firebaseapp.com',
    databaseURL:
        'https://bookstore-c7f2d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bookstore-c7f2d.firebasestorage.app',
    measurementId: 'G-YK6FK01MBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADWE9HROTFgxXQ2gbxEfp7FUktrouMbpk',
    appId: '1:234402254994:android:74fdd0709d973098ebd64b',
    messagingSenderId: '234402254994',
    projectId: 'bookstore-c7f2d',
    databaseURL:
        'https://bookstore-c7f2d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bookstore-c7f2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo1L9xzD8hJnq9Z2t0vJPJ8oCUCTs_U5w',
    appId: '1:234402254994:ios:9c718a99cdc1d7cfebd64b',
    messagingSenderId: '234402254994',
    projectId: 'bookstore-c7f2d',
    databaseURL:
        'https://bookstore-c7f2d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bookstore-c7f2d.firebasestorage.app',
    androidClientId:
        '234402254994-6l1q8o7d3228fqvfuv4g9af38sdass00.apps.googleusercontent.com',
    iosClientId:
        '234402254994-ouk20o3qk2hjrjtciev1fl796fgrseqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.booksStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo1L9xzD8hJnq9Z2t0vJPJ8oCUCTs_U5w',
    appId: '1:234402254994:ios:9c718a99cdc1d7cfebd64b',
    messagingSenderId: '234402254994',
    projectId: 'bookstore-c7f2d',
    databaseURL:
        'https://bookstore-c7f2d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bookstore-c7f2d.firebasestorage.app',
    androidClientId:
        '234402254994-6l1q8o7d3228fqvfuv4g9af38sdass00.apps.googleusercontent.com',
    iosClientId:
        '234402254994-ouk20o3qk2hjrjtciev1fl796fgrseqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.booksStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnvo13eSeBf5F-IN56Yyxw7CkAJAJVD60',
    appId: '1:234402254994:web:aa7e8674ad436426ebd64b',
    messagingSenderId: '234402254994',
    projectId: 'bookstore-c7f2d',
    authDomain: 'bookstore-c7f2d.firebaseapp.com',
    databaseURL:
        'https://bookstore-c7f2d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bookstore-c7f2d.firebasestorage.app',
    measurementId: 'G-YK6FK01MBK',
  );
}
